services:
  backend:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
      - "8081:8081"
    networks:
      - client-side
      - server-side
    volumes:
      - ./backend:/code
    depends_on:
      - mongo
    tty: true

  mongo:
    restart: always
    image: mongo:6.0.5-jammy
    env_file: backend/.env
    volumes:
      - db-data:/data/db
    networks:
      - server-side

networks:
  client-side: {}
  server-side:
    internal: true

volumes:
  db-data: {}
