services:
  backend:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
      - "8081:8081"
    volumes:
      - ./backend:/code
    depends_on:
      - mongo
    environment:
      - MONGODB_HOST=mongo:27017
    tty: true
    command: sh -c '/bin/wait-for-it.sh mongo:27017 -- python3 /code/main.py'

  mongo:
    restart: always
    image: mongo:6.0.5-jammy
    env_file: backend/.env
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}
